//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.14 at 02:54:40 AM MSK 
//

@XmlSchema(namespace = "urn:dmt:custodian2016",
        xmlns = @XmlNs(prefix = "cust", namespaceURI = "urn:dmt:custodian2016"),
        elementFormDefault = XmlNsForm.QUALIFIED)
package dmt.custodian2016;

import jakarta.xml.bind.annotation.XmlNs;
import jakarta.xml.bind.annotation.XmlNsForm;
import jakarta.xml.bind.annotation.XmlSchema;
